---

services:
  proto-compiler:
    image: ghcr.io/valentin-kaiser/protocdock:latest
    container_name: proto-compiler
    command: "/bin/bash"
    stdin_open: true
    tty: true
    volumes:
      - ./proto:/app/proto