name: ProtocDock

on: [push]

permissions:
  contents: write
  pull-requests: write

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t protocdock:local .

    - name: Compile proto files
      run: docker run --rm -v ${{ github.workspace }}:/app protocdock:local "cd proto && rm -r ./gen/ && mkdir -p ./gen/ && protoc generic.proto --plugin=ts-protoc-gen=$PROTOC_GEN_TS_PATH --go_out=./gen/ --go-grpc_out=./gen/ --js_out=\"import_style=commonjs,binary:./gen/\" --grpc-web_out=\"import_style=typescript,mode=grpcweb:./gen/\" --proto_path=/app/proto"

    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git diff --staged --quiet || git commit -m "[GEN] Updated compiled proto definitions"
        git push
